version: '3.6'
services:
  #
  # use the following to create an empty database
  # the database will be initialized with a script providing the correct schema
  # but no data.
  #
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlrootpwd
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqluserpwd
    volumes:
      - './stack/db/init:/docker-entrypoint-initdb.d'
    expose:
      - '3306'
    ports:
      - 3306:3306
  #
  # use the following to create a replica of a remote database
  #
  mirrordb:
    build:
      context: stack/mirrordb
      args:
        SOURCE_HOST_SG_DOC: your-database-host
        SOURCE_DATABASE_SG_DOC: your-database-name
        SOURCE_USER_SG_DOC: your-database-username
        SOURCE_PASSWORD_SG_DOC: your-database-password
    ports:
      - 3352:3306

  #
  # use the following to launch a MinIO instance to test S3 backbone
  #
  minio:
    image: minio/minio:RELEASE.2021-06-07T21-40-51Z
    hostname: minio
    expose:
      - '9000'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123456
    command: server /data
    volumes:
      - ./fs/minio/data:/data
    ports:
      - 9000:9000
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3
